# Generated by Django 5.0.8 on 2025-09-27 00:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Password",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Password entry title", max_length=255),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username or email for the account",
                        max_length=255,
                    ),
                ),
                (
                    "encrypted_password",
                    models.TextField(help_text="AES-256-GCM encrypted password"),
                ),
                (
                    "url",
                    models.URLField(blank=True, help_text="Website or service URL"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or information"
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=dict, help_text="Custom fields as JSON"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorization"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Password priority level",
                        max_length=20,
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this password is marked as favorite",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="When password was last accessed",
                        null=True,
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times password was accessed"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When password expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="When password was deleted", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this password",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_passwords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this password",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_passwords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group that owns this password",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passwords",
                        to="groups.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password",
                "verbose_name_plural": "Passwords",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordAccessLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When password was accessed",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of access", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "password",
                    models.ForeignKey(
                        help_text="Password that was accessed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="passwords.password",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who accessed the password",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Access Log",
                "verbose_name_plural": "Password Access Logs",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("password_changed", "Password Changed"),
                            ("deleted", "Deleted"),
                            ("restored", "Restored"),
                        ],
                        help_text="Type of change made",
                        max_length=20,
                    ),
                ),
                (
                    "previous_values",
                    models.JSONField(
                        default=dict, help_text="Previous field values before change"
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(blank=True, help_text="Summary of changes made"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="User who made the change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "password",
                    models.ForeignKey(
                        help_text="Password this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="passwords.password",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password History",
                "verbose_name_plural": "Password Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="password",
            index=models.Index(
                fields=["group", "-updated_at"], name="passwords_p_group_i_a1b49e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="password",
            index=models.Index(
                fields=["created_by", "-updated_at"],
                name="passwords_p_created_283401_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="password",
            index=models.Index(fields=["title"], name="passwords_p_title_6ce6ad_idx"),
        ),
        migrations.AddIndex(
            model_name="password",
            index=models.Index(
                fields=["is_favorite", "-updated_at"],
                name="passwords_p_is_favo_627193_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="password",
            index=models.Index(
                fields=["priority", "-updated_at"],
                name="passwords_p_priorit_348a5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="password",
            index=models.Index(
                fields=["is_deleted"], name="passwords_p_is_dele_20c495_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="password",
            index=models.Index(
                fields=["expires_at"], name="passwords_p_expires_88a0cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordaccesslog",
            index=models.Index(
                fields=["password", "-accessed_at"],
                name="passwords_p_passwor_6cea55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordaccesslog",
            index=models.Index(
                fields=["user", "-accessed_at"], name="passwords_p_user_id_893409_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordaccesslog",
            index=models.Index(
                fields=["-accessed_at"], name="passwords_p_accesse_8bc62e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(
                fields=["password", "-created_at"],
                name="passwords_p_passwor_e8c87e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(
                fields=["changed_by", "-created_at"],
                name="passwords_p_changed_8c15f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(
                fields=["change_type", "-created_at"],
                name="passwords_p_change__e0df5b_idx",
            ),
        ),
    ]
