# Generated by Django 4.2.17 on 2025-12-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("directories", "0001_initial"),
        ("passwords", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="directory",
            field=models.ForeignKey(
                blank=True,
                help_text="Directory for organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passwords",
                to="directories.directory",
            ),
        ),
    ]
