# Generated by Django 5.2 on 2025-12-10 01:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0002_password_directory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordShare",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("view", "View"), ("edit", "Edit")],
                        default="view",
                        help_text="Access permission level",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When share access expires", null=True
                    ),
                ),
                (
                    "password",
                    models.ForeignKey(
                        help_text="Password being shared",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="passwords.password",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        help_text="User who shared the password",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_passwords_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        help_text="User who received the password",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_passwords_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Share",
                "verbose_name_plural": "Password Shares",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["password", "shared_with"],
                        name="passwords_p_passwor_fbbd6e_idx",
                    ),
                    models.Index(
                        fields=["shared_with", "permission"],
                        name="passwords_p_shared__c2b809_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="passwords_p_expires_7be8fb_idx"
                    ),
                ],
                "unique_together": {("password", "shared_with")},
            },
        ),
    ]
