# Generated by Django 5.0.8 on 2026-01-27 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("password_shared", "Password Shared"),
                            ("share_revoked", "Share Revoked"),
                            ("password_access", "Password Accessed"),
                            ("system", "System"),
                        ],
                        help_text="Type of notification",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether notification has been read"
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="Optional URL to navigate to when clicked"
                    ),
                ),
                (
                    "password_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Related password ID if applicable",
                        null=True,
                    ),
                ),
                (
                    "share_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Related share ID if applicable",
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data for the notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who will receive this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(fields=["type"], name="notificatio_type_ea918f_idx"),
                ],
            },
        ),
    ]
