# Generated by Django 5.0.8 on 2025-09-26 16:50

import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["full_name", "email"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_role_0ace22_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_active_740166_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_created_6541e9_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_email_6f2530_idx",
            old_name="users_email_4b85f2_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="banned_at",
            field=models.DateTimeField(
                blank=True, help_text="When user was banned", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="banned_reason",
            field=models.TextField(blank=True, help_text="Reason for banning user"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_password_change",
            field=models.DateTimeField(
                blank=True, help_text="When user last changed their password", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="banned",
            field=models.BooleanField(
                default=False, help_text="Whether user is banned from the system"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="User's email address (used for login)",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False, help_text="Whether user's email has been verified"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(help_text="User's full name", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_reset_expires",
            field=models.DateTimeField(
                blank=True, help_text="When password reset token expires", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email_verified"], name="users_user_email_v_d8053a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["banned"], name="users_user_banned_7fc324_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-date_joined"], name="users_user_date_jo_5abcb7_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
