# Generated by Django 4.2.17 on 2025-12-03 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Directory name (max 100 characters)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional directory description"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this directory",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_directories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group that owns this directory",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directories",
                        to="groups.group",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent directory (null for root directories)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdirectories",
                        to="directories.directory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Directory",
                "verbose_name_plural": "Directories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["group", "parent", "name"],
                        name="directories_group_i_88c424_idx",
                    ),
                    models.Index(
                        fields=["group", "-created_at"],
                        name="directories_group_i_ff9d6c_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="directory",
            constraint=models.UniqueConstraint(
                fields=("group", "parent", "name"),
                name="unique_directory_name_per_parent",
            ),
        ),
    ]
