# Generated by Django 5.0.8 on 2025-09-26 16:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Group name (max 100 characters)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional group description"
                    ),
                ),
                (
                    "is_personal",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a personal vault group",
                    ),
                ),
                (
                    "encryption_key",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted group encryption key for password encryption",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - if True, record is considered deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        help_text="User's role in the group",
                        max_length=10,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When user joined the group",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who added this member to the group",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group the user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is a member of the group",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Membership",
                "verbose_name_plural": "Group Memberships",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["owner", "name"], name="groups_grou_owner_i_d44c27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["owner", "-created_at"], name="groups_grou_owner_i_17469e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["is_personal"], name="groups_grou_is_pers_82bfdd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_group_name_per_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(
                fields=["user", "group"], name="groups_user_user_id_6ff8cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(
                fields=["group", "role"], name="groups_user_group_i_75ba11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(
                fields=["group", "-joined_at"], name="groups_user_group_i_0571fd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usergroup",
            constraint=models.UniqueConstraint(
                fields=("user", "group"), name="unique_user_group_membership"
            ),
        ),
    ]
